name: CI/CD

on:
  push:
    branches: 
      - master
      - readable-workflow
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pull template
        uses: docker://utsavanand2/faas-cli:latest-root
        with:
          args: template store pull golang-http
      - 
        name: Run shrinkwrap build
        uses: docker://utsavanand2/faas-cli:latest-root
        with:
          args: build -f faasd-hello.yml --shrinkwrap
      -
        name: Login to OpenFaaS Gateway
        uses: docker://utsavanand2/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} -g ${{ secrets.OPENFAAS_GATEWAY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: List dir contents
        run: |
          ls -lah
      - 
        name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v2
        with:
          context: ./build/faasd-hello/
          file: ./build/faasd-hello/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: utsavanand2/faasd-hello:latest
      - 
        name: Deploy the function
        uses: docker://utsavanand2/faas-cli:latest-root
        with:
          args: deploy -f faasd-hello.yml
          
